### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by JiaxiangBU** [JiaxiangBU/pyks#3]
```cmd
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies
for platform win-64: {'sklearn'}
```

**Comment by JiaxiangBU** [comment]
In MacOS

```bash
 conda build .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Copying /Users/vija/Downloads/work/pyks to /Users/vija/miniconda3/conda-bld/pyks_1563990260616/work/
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for pyks
INFO:conda_build.metadata:Attempting to finalize metadata for pyks
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['pyks-0.1.1-py_1.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /Users/vija/miniconda3/conda-bld/work
  Test:
 /Users/vija/miniconda3/conda-bld/test_tmp
Leaving build/test environments:
  Test:
source activate  /Users/vija/miniconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
  Build:
source activate  /Users/vija/miniconda3/conda-bld/_build_env


Traceback (most recent call last):
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda_build/environ.py", line 756, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 112, in solve_for_transaction
    force_remove, force_reinstall)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 150, in solve_for_diff
    force_remove)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 245, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 477, in _add_specs
    explicit_pool = self._get_package_pool(ssc, self.specs_to_add)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 396, in _get_package_pool
    pool = ssc.r.get_reduced_index(specs)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 485, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 290, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - sklearn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vija/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2313, in build_tree
    notest=notest,
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1377, in build
    create_build_envs(top_level_pkg, notest)
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1279, in create_build_envs
    raise e
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1269, in create_build_envs
    channel_urls=tuple(m.config.channel_urls))
  File "/Users/vija/miniconda3/lib/python3.7/site-packages/conda_build/environ.py", line 758, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: {'sklearn'}
```

**Comment by JiaxiangBU** [comment]
```bash
conda build .
```

`sklearn` 名字错了。

**Comment by JiaxiangBU** [comment]
![image](https://user-images.githubusercontent.com/15884785/61817284-c3785180-ae80-11e9-9a7e-f3dccbbff7dc.png)

没有更新！

![image](https://user-images.githubusercontent.com/15884785/61817337-e4d93d80-ae80-11e9-9e3a-79cf076e68eb.png)


更新了

**Comment by JiaxiangBU** [comment]
本地也更新了。

![image](https://user-images.githubusercontent.com/15884785/61839204-491af200-aebf-11e9-8d2e-c6967648b9a4.png)

**Comment by JiaxiangBU** [comment]
> ![image](https://user-images.githubusercontent.com/15884785/61817284-c3785180-ae80-11e9-9a7e-f3dccbbff7dc.png)
> 
> 没有更新！

那应该就是当初上版本时，写的 v1.0.0 的问题了，后来才弄成 v.0.1.0 开始的。
这个问题暂时无解了。

**Comment by JiaxiangBU** [comment]
![image](https://user-images.githubusercontent.com/15884785/61839340-c6defd80-aebf-11e9-9628-0a4387c9e8f3.png)

我相当于版本回滚了，修改回来。
